MC-38910 Add compatibility with composer 2
magento/magento-composer-installer pull request #29
Opened 2020-11-27 11:11 UTC by jcuerdo

2020-11-30 10:45 UTC, loginesta approved these changes

2020-11-30 16:29 UTC, fascinosum requested changes

2020-12-01 09:37 UTC, jcuerdo commented on composer.json
> +            "url": "git@github.com:firegento/phpcs.git"
Flyingmana/phpcs does not exists anymore. Moved to firegento/phpcs

2020-12-01 09:47 UTC, jcuerdo commented on composer.json
> +        "firegento/phpcs": "dev-develop",
You right ¡¡ Let's use ^1.0.1

2020-12-01 09:51 UTC, jcuerdo commented on composer.json
> +        "composer/composer":"<=1.10.6|| ^2.0",
@Rrego6 you think we could use "^1.0" instead ?

Will be like "^1.0|| ^2.0"

2020-12-01 14:34 UTC, jcuerdo commented on composer.json
> +        "composer/composer":"<=1.10.6|| ^2.0",
"^2.0" is enought

2020-12-01 16:42 UTC, closed without merging